## 4.1. NumPy ndarray: 다차원 배열 객체

In [1]:
import numpy as np

In [49]:
data = np.random.randn(2,3) ## 난수를 2X3 배열로 data에 저장

In [50]:
data

array([[ 0.49751058, -0.0280452 , -0.23275395],
       [ 1.17513741, -0.85375885, -0.39380867]])

In [51]:
type(data) ## data는 ndarray 타입 변수 

numpy.ndarray

In [52]:
print(data.shape) ## data의 디멘전 
print(data.dtype) ## data에 들어있는 변수의 타입

(2L, 3L)
float64


### 4.1.1. ndarray 생성

In [55]:
data1 = [6,7.5,8,0,1] ## data1에 리스트(element가 5개) 저장 
arr1 = np.array(data1) ## np.array로 리스트를 ndarray로 변환
print(type(data1))
print(arr1)
print(type(arr1)) ## arr1은 ndarray 타입

<type 'list'>
[ 6.   7.5  8.   0.   1. ]
<type 'numpy.ndarray'>


In [56]:
data2 = [[1,2,3,4],[5,6,7,8]] ## 리스트 내에 리스트를 포함
arr2 = np.array(data2) ## data2를 2차원 배열로 변환
print(arr2) 
print(arr2.ndim) ## arr2의 디멘젼 갯수 - 2차원 배열
print(arr2.shape) ## arr2의 디멘젼

[[1 2 3 4]
 [5 6 7 8]]
2
(2L, 4L)


In [22]:
print(np.zeros(10)) ## 디멘젼에 해당하는 배열 생성 후, 0 대입
print(np.zeros((3,6)))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [59]:
print(np.empty((2,3,4,5))) ## 3차원의 배열 생성 후, 0이 아닌 값 대입
print(np.arange(15)) ## 0부터 15개의 연속적인 정수로 구성된 1차원 배열 생성 

[[[[  3.28004071e-316   0.00000000e+000   1.69759669e-313   4.94065646e-324
      3.28211247e-316]
   [  3.28000202e-316   3.27912634e-316   1.90979627e-313   0.00000000e+000
      0.00000000e+000]
   [  3.28001452e-316   0.00000000e+000   2.33419543e-313   4.94065646e-324
      3.28211050e-316]
   [  3.28000252e-316   3.27912713e-316   2.54639501e-313   0.00000000e+000
      0.00000000e+000]]

  [[  3.28325436e-316   0.00000000e+000   2.75859459e-313   4.94065646e-324
      3.28211445e-316]
   [  3.28323993e-316   3.27912792e-316   3.60739290e-313   0.00000000e+000
      0.00000000e+000]
   [  3.28325243e-316   0.00000000e+000   4.03179206e-313   4.94065646e-324
      3.28214014e-316]
   [  3.28324042e-316   3.27912871e-316   5.30498954e-313   0.00000000e+000
      0.00000000e+000]]

  [[  3.16992756e-316   0.00000000e+000   5.51718912e-313   4.94065646e-324
      3.28214212e-316]
   [  3.16991313e-316   3.27912950e-316   6.36598743e-313   0.00000000e+000
      0.00000000e+000]
   [  

### 4.1.2. ndarray의 자료형

In [60]:
arr1 = np.array([1,2,3], dtype = np.float64)
arr2 = np.array([1,2,3], dtype = np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [25]:
arr = np.array([1,2,3,4,5])
print("int type : ", arr.dtype)
arr = arr.astype(np.float64) ## 타입을 플로트로 변경
print("float type : ", arr.dtype)

('int type : ', dtype('int32'))
('float type : ', dtype('float64'))


In [61]:
arr = np.array([3.7,2.8,3.1,4.2,5.4])
print(arr)
print("float type : ", arr.dtype)
arr = arr.astype(np.int32) ## 타입을 정수로 변경, 문자열도 숫자로 변환 가능
print(arr) ## 소수점을 버림
print("int type : ", arr.dtype)

[ 3.7  2.8  3.1  4.2  5.4]
('float type : ', dtype('float64'))
[3 2 3 4 5]
('int type : ', dtype('int32'))


### 4.1.3. 배열과 스칼라 간의 연산

In [63]:
arr = np.array([[1.,2.,3.,],[4.,5.,6.]]) ## Elementwise로 연산됨
print(arr)
print(arr*arr)
print(arr-arr)

[[ 1.  2.  3.]
 [ 4.  5.  6.]]
[[  1.   4.   9.]
 [ 16.  25.  36.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### 4.1.4. 색인과 슬라이싱 기초

In [67]:
arr = np.arange(10)
print(arr)
print(arr[5]) ## 5번째 원소 리턴
print(arr[5:8]) ## 5~7번째 원소 리턴

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]


In [68]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [69]:

arr_slice = arr[5:8] ## arr_slice에 arr[5:8]이 복사되는 것이 아님 --> 주의
arr_slice[1] = 12345 
print(arr)
arr_slice[:] = 77 
print(arr)

[    0     1     2     3     4     5 12345     7     8     9]
[ 0  1  2  3  4 77 77 77  8  9]


In [70]:
arr2d = np.array([np.arange(3),np.arange(3)+3,np.arange(3)+6])

In [71]:
print(arr2d)
print(arr2d[0][1])
print(arr2d[0,1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
1
1


In [72]:
arr2d[:2] ## 0,1번째 행 리턴

array([[0, 1, 2],
       [3, 4, 5]])

In [48]:
arr2d[:2,1:] ## 0,1번째 행 + 1,2번쨰 열 리턴

array([[1, 2],
       [4, 5]])

### 4.1.5. 불리언 색인

In [ ]:
names